[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

[tools]
"uv" = "0.9.28"
"aqua:casey/just" = "1.46.0"
"aqua:derailed/k9s" = "0.50.18"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:helm/helm" = "4.1.0"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.0"
"aqua:kubernetes/kubectl" = "1.33.2"
"aqua:mikefarah/yq" = "4.52.2"
"pipx:flux-local" = "8.1.0"
