[env]
JUST_UNSTABLE = "1"
KUBECONFIG = "{{config_root}}/kubeconfig"

[tools]
"uv" = "0.9.21"
"aqua:casey/just" = "1.45.0"
"aqua:derailed/k9s" = "0.50.16"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:helm/helm" = "3.19.4"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.0"
"aqua:kubernetes/kubectl" = "1.33.2"
"aqua:mikefarah/yq" = "4.50.1"
"pipx:flux-local" = "8.1.0"
