[env]
KUBECONFIG = "{{config_root}}/kubeconfig"

[tools]
"uv" = "0.9.10"
"aqua:casey/just" = "1.43.1"
"aqua:derailed/k9s" = "0.50.16"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:helmfile/helmfile" = "1.2.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.0"
"aqua:kubernetes/kubectl" = "1.33.2"
"aqua:mikefarah/yq" = "4.48.2"
"pipx:flux-local" = "8.0.1"
