---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nlecoy-fr
spec:
  dnsNames:
    - nlecoy.fr
    - "*.nlecoy.fr"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: nlecoy-fr-tls
  usages:
    - digital signature
